"""
RAG search API routes.

POST /api/rag/search          → full RAG pipeline, returns answer + sources
POST /api/rag/stream          → streaming RAG response (Server-Sent Events)
POST /api/rag/similar         → find similar chunks without LLM
"""

import logging
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from sqlmodel import Session

from app.database import get_session
from app.services.rag_service import search_and_answer, stream_answer
from app.services.chroma_service import query_collection
from app.services.embedding_service import embed_query
from app.services.config_service import get_value

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/rag", tags=["rag"])

DbSession = Annotated[Session, Depends(get_session)]


# ── Schemas ───────────────────────────────────────────────────────────────────

class SearchRequest(BaseModel):
    query: str = Field(min_length=1, max_length=1000)
    n_results: int = Field(default=5, ge=1, le=20)


class SearchResponse(BaseModel):
    answer: str
    sources: list[dict]
    query: str


class SimilarChunksRequest(BaseModel):
    query: str = Field(min_length=1, max_length=1000)
    n_results: int = Field(default=5, ge=1, le=20)


# ── Routes ────────────────────────────────────────────────────────────────────

@router.post("/search", response_model=SearchResponse)
async def search(payload: SearchRequest, session: DbSession):
    """
    Full RAG search pipeline.
    Embeds the query, retrieves relevant chunks, generates an LLM answer.
    """
    if not payload.query.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Query must not be empty.",
        )

    result = await search_and_answer(
        query=payload.query,
        session=session,
        n_results=payload.n_results,
    )
    return SearchResponse(**result)


@router.post("/stream")
async def stream_search(payload: SearchRequest, session: DbSession):
    """
    Streaming RAG search via Server-Sent Events.
    The frontend receives tokens as they are generated by the LLM.

    SSE format:
      data: <token>\n\n
      data: [DONE]\n\n
    """
    async def event_generator():
        try:
            async for token in stream_answer(
                query=payload.query,
                session=session,
                n_results=payload.n_results,
            ):
                # Escape newlines in SSE data field
                safe_token = token.replace("\n", "\\n")
                yield f"data: {safe_token}\n\n"
        except Exception as exc:
            logger.exception("Streaming RAG error")
            yield f"data: [ERROR] {exc}\n\n"
        finally:
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",   # disable nginx buffering
        },
    )


@router.post("/similar")
async def find_similar(payload: SimilarChunksRequest, session: DbSession):
    """
    Find similar document chunks without calling the LLM.
    Useful for debugging and exploring the index.
    """
    emb_config = {
        "provider": get_value(session, "embedding_provider") or "",
        "base_url": get_value(session, "embedding_base_url") or "",
        "api_key": get_value(session, "embedding_api_key") or "",
        "model": get_value(session, "embedding_model") or "",
    }

    if not emb_config["model"]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Embedding model is not configured.",
        )

    query_embedding = await embed_query(
        payload.query,
        provider=emb_config["provider"],
        base_url=emb_config["base_url"],
        api_key=emb_config["api_key"],
        model=emb_config["model"],
    )

    chunks = query_collection(query_embedding, n_results=payload.n_results)

    return {
        "query": payload.query,
        "results": chunks,
    }